# Markdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

# Theme
theme: jekyll-theme-hacker
title: Felipe Flores
description: Software Engineer
show_downloads: false